//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthLiveSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EarthLiveSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确认退出吗？ 的本地化字符串。
        /// </summary>
        internal static string MainForm_Are_you_sure_you_want_to_quit {
            get {
                return ResourceManager.GetString("MainForm_Are_you_sure_you_want_to_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启动 的本地化字符串。
        /// </summary>
        internal static string MainForm_Has_Running {
            get {
                return ResourceManager.GetString("MainForm_Has_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启动 的本地化字符串。
        /// </summary>
        internal static string MainForm_Not_Running {
            get {
                return ResourceManager.GetString("MainForm_Not_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string MainForm_Quit {
            get {
                return ResourceManager.GetString("MainForm_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行中 的本地化字符串。
        /// </summary>
        internal static string MainForm_Running {
            get {
                return ResourceManager.GetString("MainForm_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务已启动 的本地化字符串。
        /// </summary>
        internal static string MainForm_Service_already_running {
            get {
                return ResourceManager.GetString("MainForm_Service_already_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务没有启动 的本地化字符串。
        /// </summary>
        internal static string MainForm_Service_is_not_currently_running {
            get {
                return ResourceManager.GetString("MainForm_Service_is_not_currently_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EarthLive 运行中 的本地化字符串。
        /// </summary>
        internal static string MainForm_Service_is_running {
            get {
                return ResourceManager.GetString("MainForm_Service_is_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string MainForm_Setting {
            get {
                return ResourceManager.GetString("MainForm_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        internal static string MainForm_Start_Service {
            get {
                return ResourceManager.GetString("MainForm_Start_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string MainForm_Stop_Service {
            get {
                return ResourceManager.GetString("MainForm_Stop_Service", resourceCulture);
            }
        }
    }
}
